# Generated by Django 3.0.5 on 2020-07-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='orderItem',
            new_name='item',
        ),
    ]
