# Generated by Django 3.0.5 on 2020-08-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200815_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Item', max_length=32),
            preserve_default=False,
        ),
    ]
