# Generated by Django 3.0.5 on 2020-08-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200818_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
